pipeline {
    agent {
        kubernetes {
            yamlFile 'k8s/kaniko/pod.yaml'
        }
    }

    environment {
        NAMESPACE = "kisacloud2407"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Build Docker Image with Kaniko') {
            steps {
                container('kaniko') {
                    script {
                        sh """
                        /kaniko/executor \
                            --context /workspace \
                            --dockerfile /workspace/workspace/backend/k8s/was/Dockerfile \
                            --destination docker.io/jeongseulho/wildflower-gardening:${IMAGE_TAG} \
                        """
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                kubectl apply -f k8s/deployment.yaml -n ${NAMESPACE}
                """
            }
        }
    }
}
