pipeline {
    agent any

    stages {
        
        stage('github-clone') {
            steps {
                script {
                    echo 'Starting the pipeline...'
                }
            }
        }
    }
}
