pipeline {
    agent {
        kubernetes {
            yamlFile 'k8s/jenkins/kanikoPod.yaml'
            podRetention(always())
        }
    }

    environment {
        NAMESPACE = "kisacloud2407"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    echo "Checking out the repository"
                    checkout scm
                }
            }
        }

        stage('Build Docker Image with Kaniko') {
            steps {
                container('kaniko') {
                    script {
                        echo "Building Docker Image with Kaniko"
                        sh """
                        /kaniko/executor \
                            --context /workspace \
                            --dockerfile /workspace/k8s/was/Dockerfile \
                            --destination docker.io/jeongseulho/wildflower-gardening:${IMAGE_TAG} \
                            --verbosity=debug
                        """
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo "Deploying to Kubernetes"
                sh """
                kubectl apply -f k8s/deployment.yaml -n ${NAMESPACE}
                """
            }
        }
    }
}
