apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: kisacloud2407
spec:
  selector:
    app: jenkins-server
  type: ClusterIP
  ports:
    - name: jnlpport
      port: 50000
      targetPort: 50000
