apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-admin
  namespace: kisacloud2407
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'create', 'update', 'delete']
  - apiGroups: ['']
    resources: ['pods', 'secrets']
    verbs: ['get', 'list', 'create', 'delete']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['create', 'delete', 'list', 'watch']

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: kisacloud2407
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-binding
  namespace: kisacloud2407
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-admin
subjects:
  - kind: ServiceAccount
    name: jenkins-admin
    namespace: kisacloud2407
