apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: kisacloud2407
spec:
  selector:
    app: jenkins-server
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
      nodePort: 32001
    - name: jnlpport
      port: 50000
      targetPort: 50000
  type: NodePort
