apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-admin
  namespace: kisacloud2407
rules:
  - apiGroups: ['']
    resources: ['persistentvolumeclaims', 'pods', 'services']
    verbs: ['get', 'list', 'create', 'update', 'delete']
  - apiGroups: ['apps']
    resources: ['statefulsets']
    verbs: ['get', 'list', 'create', 'update', 'delete']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['create', 'delete', 'get', 'list']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-admin
  namespace: kisacloud2407
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-admin-binding
  namespace: kisacloud2407
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-admin
subjects:
  - kind: ServiceAccount
    name: mysql-admin
    namespace: kisacloud2407
