apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kisacloud2407
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32306
  selector:
    app: mysql
