apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: kisacloud2407
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: ${IMAGE_NAME}:${IMAGE_TAG}